### ISSUE TITLE
Porting bootloader to STM32F4xx platform

### ISSUE THREAD

**Issue by PlaneStuffRC** [Zubax/zubax_gnss#12]
Hi,

I'm working to port the bootloader to STM32F405, so far , what i did was to change these:
 
In board.h and mcuconf.h:

#define STM32_HSECLK            8000000
#define STM32_LSECLK            1
#define STM32_VDD 300
#define STM32F4XX
#define STM32F405xx
#define STM32F40_41xxx
#define STM32F4xx_MCUCONF

Also in makefile :+1: 
include zubax_chibios/rules_stm32f40x.mk

And create the rules_stm32f40x.mk file 

CHIBIOS := $(ZUBAX_CHIBIOS_DIR)/chibios
include $(CHIBIOS)/os/common/ports/ARMCMx/compilers/GCC/mk/startup_stm32f4xx.mk
include $(CHIBIOS)/os/hal/ports/STM32/STM32F4xx/platform.mk
include $(CHIBIOS)/os/rt/ports/ARMCMx/compilers/GCC/mk/port_v7m.mk

LDSCRIPT ?= $(PORTLD)/STM32F405xG.ld

After all of these it's complaining about clocking issues, and i suspect there are some wrong include files 
zubax_chibios//chibios/os/hal/ports/STM32/STM32F4xx/hal_lld.h:1115:2: error: #error "STM32_PLLVCO outside acceptable range (STM32_PLLVCO_MIN...STM32_PLLVCO_MAX)"

Thanks,
Adrian.

**Comment by pavel-kirienko** [comment]
Apparently, you have to check your clock tree configs. Read the reference manual for your MCU.

Also, don't use `zubax_chibios`, it's archived and deprecated; instead, add a direct dependency on ChibiOS and use Kocherga, [as described in the README](https://github.com/Zubax/zubax_chibios/blob/master/README.md).
