### ISSUE TITLE
Migrate to UAVCAN v1.0

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/zubax_gnss#14]
UAVCAN v0 is reaching the end of its lifecycle, soon to be replaced with UAVCAN v1.0 - the first stable release of the protocol. More info here: https://forum.uavcan.org/t/stockholm-summit-recap/170

Zubax GNSS 2 will be updated to support UAVCAN v1.0 instead of v0.

**Comment by pavel-kirienko** [comment]
Relevant context https://forum.uavcan.org/t/uavcan-2019-roadmap/666

**Comment by vmsav** [comment]
@pavel-kirienko, when do you expect release of gnss 2 firmware with cyphal?

**Comment by pavel-kirienko** [comment]
@vmsav There are currently no plans to port the GNSS 2 firmare to Cyphal. Instead, we are planning to release a new device in collaboration with RaccoonLab (@frontw) that will supersede GNSS 2.

**Comment by frontw** [comment]
> @vmsav There are currently no plans to port the GNSS 2 firmare to Cyphal. Instead, we are planning to release a new device in collaboration with RaccoonLab (@frontw) that will supersede GNSS 2.

More details on current devices and interface are here https://docs.raccoonlab.co/guide/gps_mag_baro More updates are comming
