### ISSUE TITLE
cc1plus Werror

### ISSUE THREAD

**Issue by exodvs** [Zubax/zubax_gnss#18]
Whenever I attempt "make binaries" on the Raspberry Pi, I get the following error messages.

Compiling main.cpp
cc1plus: error: -Werror=implicit-fallthrough: no option -Wimplicit-fallthrough
cc1plus: error: -Werror=bool-operation: no option -Wbool-operation
zubax_chibios///chibios/os/common/ports/ARMCMx/compilers/GCC/rules.mk:198: recipe for target 'build/obj/main.o' failed
make: *** [build/obj/main.o] Error 1

I also had to separately clone libuavcan and zubax_chibios. Might that have something to do with it?

**Comment by pavel-kirienko** [comment]
You need ARM GCC version 7.3.1.
